---
- name: Query sessions
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Query sessions
    command: /sbin/iscsiadm -m sessions
    register: sessions
    failed_when: sessions.rc not in (0,21)    
