---
- name: Checking Vault
  hosts: all
  gather_facts: false
  
  tasks:
  - name: First task
    debug:
      msg: "{{ ansible_ssh_host}}"
  
  - name: Second Task
    debug:
      msg: "Hello User"
